### ISSUE TITLE
Redirect method failure

### ISSUE THREAD

**Issue by dravenk** [aspendigital/docker-codeigniter#1]
I've test this image with ci3. This image not make redirect() work well.
This is come code of docker-compose.yml
```
...
myapp:
    image: 'aspendigital/codeigniter:latest'
    restart: always
    ports:
      - '8882:80'
...
```
And some custom code of app like this.
```
 redirect('/admin/index/index');
```
After run this method. It will show the IP address of the container.
I see `http://172.18.0.4/admin/index/index` 
expect:
`http://localhost:8882/admin/index/index`
